/**
 * Generated by `bun run deployment-config:generate` from the canonical OAuth
 * registry and integration catalog. Do not edit this file directly.
 */
export const SERVICE_ACCOUNT_PROVIDER_BY_OAUTH_SERVICE_ID = {
  airtable: 'airtable-service-account',
  calcom: 'calcom-service-account',
  gmail: 'google-service-account',
  'google-calendar': 'google-service-account',
  'google-docs': 'google-service-account',
  'google-drive': 'google-service-account',
  'google-forms': 'google-service-account',
  'google-sheets': 'google-service-account',
  hubspot: 'hubspot-service-account',
  notion: 'notion-service-account',
  pipedrive: 'pipedrive-service-account',
  shopify: 'shopify-service-account',
  trello: 'trello-service-account',
  zoom: 'zoom-service-account',
} as const

/** OAuth services whose users supply app credentials when connecting an account. */
export const CREDENTIAL_CONFIGURED_OAUTH_SERVICE_IDS = [] as const
