import type { IconLibrary, IconSchema } from './schema'

const BASE = 'https://arenav2image.s3.us-west-1.amazonaws.com/presentation-icons'

const blackIcons: IconSchema[] = [
  {
    id: 'ai-adaptation-generic',
    label: 'AI Adaptation',
    category: 'generic',
    color: 'black',
    tags: [
      'ai',
      'artificial intelligence',
      'adaptation',
      'machine learning',
      'smart',
      'automation',
    ],
    pngUrl: `${BASE}/black/generic/ai+adaptation.png`,
  },
  {
    id: 'app-development-generic',
    label: 'App Development',
    category: 'generic',
    color: 'black',
    tags: ['app', 'development', 'mobile', 'software', 'build', 'product', 'engineering'],
    pngUrl: `${BASE}/black/generic/app+development.png`,
  },
  {
    id: 'campaign-marketing-generic',
    label: 'Campaign Marketing',
    category: 'generic',
    color: 'black',
    tags: ['campaign', 'marketing', 'advertising', 'promotion', 'outreach', 'brand'],
    pngUrl: `${BASE}/black/generic/campaign+marketing.png`,
  },
  {
    id: 'company-growth-generic',
    label: 'company growth',
    category: 'generic',
    color: 'black',
    tags: ['growth', 'company', 'expansion', 'scale', 'business', 'success', 'progress'],
    pngUrl: `${BASE}/black/generic/company+growth.png`,
  },
  {
    id: 'creative-content-generic',
    label: 'Creative Content',
    category: 'generic',
    color: 'black',
    tags: ['creative', 'content', 'design', 'media', 'storytelling', 'writing', 'copy'],
    pngUrl: `${BASE}/black/generic/creative+content.png`,
  },
  {
    id: 'creative-process-generic',
    label: 'Creative Process',
    category: 'generic',
    color: 'black',
    tags: [
      'creative',
      'process',
      'ideation',
      'brainstorm',
      'design thinking',
      'innovation',
      'workflow',
    ],
    pngUrl: `${BASE}/black/generic/creative+process.png`,
  },
  {
    id: 'deploy-generic',
    label: 'Deploy',
    category: 'generic',
    color: 'black',
    tags: ['deploy', 'launch', 'release', 'ship', 'publish', 'go-live', 'production'],
    pngUrl: `${BASE}/black/generic/deploy.png`,
  },
  {
    id: 'laptop-settings-generic',
    label: 'Laptop Settings',
    category: 'generic',
    color: 'black',
    tags: ['laptop', 'settings', 'configuration', 'device', 'setup', 'system', 'it'],
    pngUrl: `${BASE}/black/generic/laptop+settings.png`,
  },
  {
    id: 'leadership-change-generic',
    label: 'Leadership Change',
    category: 'generic',
    color: 'black',
    tags: ['leadership', 'change', 'management', 'transition', 'strategy', 'direction', 'vision'],
    pngUrl: `${BASE}/black/generic/leadership+change.png`,
  },
  {
    id: 'partnership-generic',
    label: 'Partnership',
    category: 'generic',
    color: 'black',
    tags: ['partnership', 'collaboration', 'alliance', 'joint', 'together', 'team', 'relations'],
    pngUrl: `${BASE}/black/generic/partnership.png`,
  },
  {
    id: 'revenue-generic',
    label: 'Revenue',
    category: 'generic',
    color: 'black',
    tags: ['revenue', 'income', 'sales', 'profit', 'money', 'earnings', 'roi'],
    pngUrl: `${BASE}/black/generic/revenue.png`,
  },
  {
    id: 'user-experience-generic',
    label: 'User Experience',
    category: 'generic',
    color: 'black',
    tags: ['ux', 'user experience', 'design', 'usability', 'interface', 'journey', 'product'],
    pngUrl: `${BASE}/black/generic/user+experience.png`,
  },
  {
    id: 'user-interaction-generic',
    label: 'User Interaction',
    category: 'generic',
    color: 'black',
    tags: ['user', 'interaction', 'engagement', 'click', 'behavior', 'interface', 'action'],
    pngUrl: `${BASE}/black/generic/user+interaction.png`,
  },
  {
    id: 'customer-support-marketing',
    label: 'Customer Support',
    category: 'marketing',
    color: 'black',
    tags: ['customer', 'support', 'service', 'help', 'assistance', 'care', 'helpdesk'],
    pngUrl: `${BASE}/black/marketing/customer+support.png`,
  },
  {
    id: 'global-campaign-marketing',
    label: 'Global Campaign',
    category: 'marketing',
    color: 'black',
    tags: ['global', 'campaign', 'international', 'worldwide', 'reach', 'market', 'expansion'],
    pngUrl: `${BASE}/black/marketing/global+campaign.png`,
  },
  {
    id: 'keyword-search-marketing',
    label: 'Keyword Search',
    category: 'marketing',
    color: 'black',
    tags: ['keyword', 'search', 'seo', 'query', 'terms', 'discovery', 'targeting'],
    pngUrl: `${BASE}/black/marketing/keyword+search.png`,
  },
  {
    id: 'marketing-automation-marketing',
    label: 'Marketing Automation',
    category: 'marketing',
    color: 'black',
    tags: ['automation', 'marketing', 'workflow', 'trigger', 'sequence', 'nurture', 'pipeline'],
    pngUrl: `${BASE}/black/marketing/marketing+automation.png`,
  },
  {
    id: 'network-option1-marketing',
    label: 'Network Option 1',
    category: 'marketing',
    color: 'black',
    tags: ['network', 'connection', 'infrastructure', 'nodes', 'web', 'ecosystem', 'platform'],
    pngUrl: `${BASE}/black/marketing/network+option+1.png`,
  },
  {
    id: 'network-option2-marketing',
    label: 'Network Option 2',
    category: 'marketing',
    color: 'black',
    tags: ['network', 'connection', 'infrastructure', 'nodes', 'web', 'ecosystem', 'platform'],
    pngUrl: `${BASE}/black/marketing/network+option+2.png`,
  },
  {
    id: 'responsive-marketing',
    label: 'Responsive',
    category: 'marketing',
    color: 'black',
    tags: ['responsive', 'mobile', 'adaptive', 'design', 'device', 'screen', 'layout'],
    pngUrl: `${BASE}/black/marketing/responsive.png`,
  },
  {
    id: 'sitemap-marketing',
    label: 'Sitemap',
    category: 'marketing',
    color: 'black',
    tags: ['sitemap', 'structure', 'navigation', 'architecture', 'pages', 'crawl', 'index'],
    pngUrl: `${BASE}/black/marketing/sitemap.png`,
  },
  {
    id: 'social-network-marketing',
    label: 'Social Network',
    category: 'marketing',
    color: 'black',
    tags: ['social', 'network', 'media', 'community', 'platform', 'engagement', 'followers'],
    pngUrl: `${BASE}/black/marketing/social+network.png`,
  },
  {
    id: 'team-building-marketing',
    label: 'Team Building',
    category: 'marketing',
    color: 'black',
    tags: ['team', 'building', 'people', 'culture', 'collaboration', 'hiring', 'talent'],
    pngUrl: `${BASE}/black/marketing/teambuilding.png`,
  },
  {
    id: 'active-search-seo',
    label: 'Active Search',
    category: 'seo',
    color: 'black',
    tags: ['search', 'find', 'lookup', 'discovery', 'research', 'query', 'seo'],
    pngUrl: `${BASE}/black/seo/active+search.png`,
  },
  {
    id: 'calendar-seo',
    label: 'Calendar',
    category: 'seo',
    color: 'black',
    tags: ['calendar', 'schedule', 'planning', 'time', 'date', 'events', 'meeting'],
    pngUrl: `${BASE}/black/seo/calendar.png`,
  },
  {
    id: 'chat-seo',
    label: 'Chat',
    category: 'seo',
    color: 'black',
    tags: ['chat', 'message', 'conversation', 'communication', 'support', 'dialogue'],
    pngUrl: `${BASE}/black/seo/chat.png`,
  },
  {
    id: 'cloud-sync-seo',
    label: 'Cloud Sync',
    category: 'seo',
    color: 'black',
    tags: ['cloud', 'sync', 'backup', 'storage', 'integration', 'data', 'upload'],
    pngUrl: `${BASE}/black/seo/cloud+sync.png`,
  },
  {
    id: 'coding-seo',
    label: 'Coding',
    category: 'seo',
    color: 'black',
    tags: ['coding', 'programming', 'development', 'engineering', 'software', 'code'],
    pngUrl: `${BASE}/black/seo/coding.png`,
  },
  {
    id: 'data-analytics-seo',
    label: 'Data Analytics',
    category: 'seo',
    color: 'black',
    tags: ['data', 'analytics', 'insights', 'metrics', 'reporting', 'analysis', 'dashboard'],
    pngUrl: `${BASE}/black/seo/data+analystics.png`,
  },
  {
    id: 'data-download-seo',
    label: 'Data Download',
    category: 'seo',
    color: 'black',
    tags: ['data', 'download', 'export', 'transfer', 'extract', 'retrieve'],
    pngUrl: `${BASE}/black/seo/data+download.png`,
  },
  {
    id: 'email-marketing-option1-seo',
    label: 'Email Marketing Option 1',
    category: 'seo',
    color: 'black',
    tags: ['email', 'marketing', 'newsletter', 'outreach', 'campaign', 'inbox'],
    pngUrl: `${BASE}/black/seo/email+marketing+option+1.png`,
  },
  {
    id: 'email-marketing-option2-seo',
    label: 'Email Marketing Option 2',
    category: 'seo',
    color: 'black',
    tags: ['email', 'marketing', 'newsletter', 'outreach', 'campaign', 'inbox'],
    pngUrl: `${BASE}/black/seo/email+marketing+option+2.png`,
  },
  {
    id: 'increased-performance-seo',
    label: 'Increased Performance',
    category: 'seo',
    color: 'black',
    tags: ['performance', 'increase', 'improve', 'optimize', 'boost', 'efficiency', 'results'],
    pngUrl: `${BASE}/black/seo/increased+performance.png`,
  },
  {
    id: 'link-seo',
    label: 'Link',
    category: 'seo',
    color: 'black',
    tags: ['link', 'connect', 'integration', 'url', 'backlink', 'reference', 'chain'],
    pngUrl: `${BASE}/black/seo/link.png`,
  },
  {
    id: 'online-support-seo',
    label: 'Online Support',
    category: 'seo',
    color: 'black',
    tags: ['online', 'support', 'helpdesk', 'service', 'chat', 'remote', 'assistance'],
    pngUrl: `${BASE}/black/seo/online+support.png`,
  },
  {
    id: 'seo-location-seo',
    label: 'SEO Location',
    category: 'seo',
    color: 'black',
    tags: ['seo', 'location', 'local', 'geo', 'map', 'targeting', 'search'],
    pngUrl: `${BASE}/black/seo/seo+location.png`,
  },
  {
    id: 'seo-option1-seo',
    label: 'SEO Option 1',
    category: 'seo',
    color: 'black',
    tags: ['seo', 'optimization', 'search', 'ranking', 'organic', 'visibility', 'engine'],
    pngUrl: `${BASE}/black/seo/seo+option+1.png`,
  },
  {
    id: 'seo-option2-seo',
    label: 'SEO Option 2',
    category: 'seo',
    color: 'black',
    tags: ['seo', 'optimization', 'search', 'ranking', 'organic', 'visibility', 'engine'],
    pngUrl: `${BASE}/black/seo/seo+option+2.png`,
  },
  {
    id: 'seo-plugin-option2-seo',
    label: 'SEO Plugin Option 2',
    category: 'seo',
    color: 'black',
    tags: ['seo', 'plugin', 'tool', 'optimization', 'search', 'ranking', 'engine'],
    pngUrl: `${BASE}/black/seo/seo+plugin+option+2.png`,
  },
  {
    id: 'seo-plugin-seo',
    label: 'SEO Plugin',
    category: 'seo',
    color: 'black',
    tags: ['seo', 'plugin', 'tool', 'optimization', 'search', 'ranking', 'engine'],
    pngUrl: `${BASE}/black/seo/seo+plugin.png`,
  },
  {
    id: 'seo-seo',
    label: 'SEO',
    category: 'seo',
    color: 'black',
    tags: ['seo', 'search engine optimization', 'ranking', 'organic', 'visibility', 'traffic'],
    pngUrl: `${BASE}/black/seo/seo.png`,
  },
  {
    id: 'target-seo',
    label: 'Target',
    category: 'seo',
    color: 'black',
    tags: ['target', 'audience', 'goal', 'focus', 'aim', 'precision', 'segment'],
    pngUrl: `${BASE}/black/seo/target.png`,
  },
  {
    id: 'time-management-seo',
    label: 'Time Management',
    category: 'seo',
    color: 'black',
    tags: ['time', 'management', 'efficiency', 'planning', 'deadline', 'schedule', 'productivity'],
    pngUrl: `${BASE}/black/seo/time+management.png`,
  },
  {
    id: 'traffic-seo',
    label: 'Traffic',
    category: 'seo',
    color: 'black',
    tags: ['traffic', 'visits', 'sessions', 'users', 'web', 'inbound', 'acquisition'],
    pngUrl: `${BASE}/black/seo/traffic.png`,
  },
  {
    id: 'video-marketing-seo',
    label: 'Video Marketing',
    category: 'seo',
    color: 'black',
    tags: ['video', 'marketing', 'content', 'media', 'youtube', 'visual', 'campaign'],
    pngUrl: `${BASE}/black/seo/video+marketing.png`,
  },
  {
    id: 'web-optimisation-seo',
    label: 'Web Optimisation',
    category: 'seo',
    color: 'black',
    tags: ['web', 'optimisation', 'performance', 'speed', 'core web vitals', 'loading', 'site'],
    pngUrl: `${BASE}/black/seo/web+optimisation.png`,
  },
]

const whiteIcons: IconSchema[] = [
  {
    id: 'ai-adaptation-generic-white',
    label: 'AI Adaptation',
    category: 'generic',
    color: 'white',
    tags: [
      'ai',
      'artificial intelligence',
      'adaptation',
      'machine learning',
      'smart',
      'automation',
    ],
    pngUrl: `${BASE}/white/generic/ai+adaptation+-+white.png`,
  },
  {
    id: 'app-development-generic-white',
    label: 'App Development',
    category: 'generic',
    color: 'white',
    tags: ['app', 'development', 'mobile', 'software', 'build', 'product', 'engineering'],
    pngUrl: `${BASE}/white/generic/app+development+-+white.png`,
  },
  {
    id: 'campaign-marketing-generic-white',
    label: 'Campaign Marketing',
    category: 'generic',
    color: 'white',
    tags: ['campaign', 'marketing', 'advertising', 'promotion', 'outreach', 'brand'],
    pngUrl: `${BASE}/white/generic/campaign+marketing+-+white.png`,
  },
  {
    id: 'company-growth-generic-white',
    label: 'Company Growth',
    category: 'generic',
    color: 'white',
    tags: ['growth', 'company', 'expansion', 'scale', 'business', 'success', 'progress'],
    pngUrl: `${BASE}/white/generic/company+growth+white.png`,
  },
  {
    id: 'creative-content-generic-white',
    label: 'Creative Content',
    category: 'generic',
    color: 'white',
    tags: ['creative', 'content', 'design', 'media', 'storytelling', 'writing', 'copy'],
    pngUrl: `${BASE}/white/generic/creative+content-white.png`,
  },
  {
    id: 'thinking-process-generic-white',
    label: 'Thinking Process',
    category: 'generic',
    color: 'white',
    tags: ['thinking', 'process', 'strategy', 'planning', 'ideation', 'brainstorm', 'decision'],
    pngUrl: `${BASE}/white/generic/thinking+process.png`,
  },
  {
    id: 'deploy-generic-white',
    label: 'Deploy',
    category: 'generic',
    color: 'white',
    tags: ['deploy', 'launch', 'release', 'ship', 'publish', 'go-live', 'production'],
    pngUrl: `${BASE}/white/generic/deploy-white.png`,
  },
  {
    id: 'laptop-settings-generic-white',
    label: 'Laptop Settings',
    category: 'generic',
    color: 'white',
    tags: ['laptop', 'settings', 'configuration', 'device', 'setup', 'system', 'it'],
    pngUrl: `${BASE}/white/generic/laptop+settings-white.png`,
  },
  {
    id: 'leadership-change-generic-white',
    label: 'Leadership Change',
    category: 'generic',
    color: 'white',
    tags: ['leadership', 'change', 'management', 'transition', 'strategy', 'direction', 'vision'],
    pngUrl: `${BASE}/white/generic/leadership+change+white.png`,
  },
  {
    id: 'partnership-generic-white',
    label: 'Partnership',
    category: 'generic',
    color: 'white',
    tags: ['partnership', 'collaboration', 'alliance', 'joint', 'together', 'team', 'relations'],
    pngUrl: `${BASE}/white/generic/partnership+-+white.png`,
  },
  {
    id: 'revenue-generic-white',
    label: 'Revenue',
    category: 'generic',
    color: 'white',
    tags: ['revenue', 'income', 'sales', 'profit', 'money', 'earnings', 'roi'],
    pngUrl: `${BASE}/white/generic/revenue+white.png`,
  },
  {
    id: 'user-experience-generic-white',
    label: 'User Experience',
    category: 'generic',
    color: 'white',
    tags: ['ux', 'user experience', 'design', 'usability', 'interface', 'journey', 'product'],
    pngUrl: `${BASE}/white/generic/user+experience.png`,
  },
  {
    id: 'user-interaction-generic-white',
    label: 'User Interaction',
    category: 'generic',
    color: 'white',
    tags: ['user', 'interaction', 'engagement', 'click', 'behavior', 'interface', 'action'],
    pngUrl: `${BASE}/white/generic/user+interaction-white.png`,
  },
  {
    id: 'customer-support-marketing-white',
    label: 'Customer Support',
    category: 'marketing',
    color: 'white',
    tags: ['customer', 'support', 'service', 'help', 'assistance', 'care', 'helpdesk'],
    pngUrl: `${BASE}/white/marketing/customer+support+white.png`,
  },
  {
    id: 'global-campaign-marketing-white',
    label: 'Global Campaign',
    category: 'marketing',
    color: 'white',
    tags: ['global', 'campaign', 'international', 'worldwide', 'reach', 'market', 'expansion'],
    pngUrl: `${BASE}/white/marketing/global+campaign+white.png`,
  },
  {
    id: 'keyword-search-marketing-white',
    label: 'Keyword Search',
    category: 'marketing',
    color: 'white',
    tags: ['keyword', 'search', 'seo', 'query', 'terms', 'discovery', 'targeting'],
    pngUrl: `${BASE}/white/marketing/keyword+search+white.png`,
  },
  {
    id: 'marketing-automation-marketing-white',
    label: 'Marketing Automation',
    category: 'marketing',
    color: 'white',
    tags: ['automation', 'marketing', 'workflow', 'trigger', 'sequence', 'nurture', 'pipeline'],
    pngUrl: `${BASE}/white/marketing/marketing+automation+white.png`,
  },
  {
    id: 'network-option1-marketing-white',
    label: 'Network Option 1',
    category: 'marketing',
    color: 'white',
    tags: ['network', 'connection', 'infrastructure', 'nodes', 'web', 'ecosystem', 'platform'],
    pngUrl: `${BASE}/white/marketing/network+option+1+white.png`,
  },
  {
    id: 'network-option2-marketing-white',
    label: 'Network Option 2',
    category: 'marketing',
    color: 'white',
    tags: ['network', 'connection', 'infrastructure', 'nodes', 'web', 'ecosystem', 'platform'],
    pngUrl: `${BASE}/white/marketing/network+option+2+white.png`,
  },
  {
    id: 'responsive-marketing-white',
    label: 'Responsive',
    category: 'marketing',
    color: 'white',
    tags: ['responsive', 'mobile', 'adaptive', 'design', 'device', 'screen', 'layout'],
    pngUrl: `${BASE}/white/marketing/responsive+white.png`,
  },
  {
    id: 'sitemap-marketing-white',
    label: 'Sitemap',
    category: 'marketing',
    color: 'white',
    tags: ['sitemap', 'structure', 'navigation', 'architecture', 'pages', 'crawl', 'index'],
    pngUrl: `${BASE}/white/marketing/sitemap+white.png`,
  },
  {
    id: 'social-network-marketing-white',
    label: 'Social Network',
    category: 'marketing',
    color: 'white',
    tags: ['social', 'network', 'media', 'community', 'platform', 'engagement', 'followers'],
    pngUrl: `${BASE}/white/marketing/social+network+white.png`,
  },
  {
    id: 'team-building-marketing-white',
    label: 'Team Building',
    category: 'marketing',
    color: 'white',
    tags: ['team', 'building', 'people', 'culture', 'collaboration', 'hiring', 'talent'],
    pngUrl: `${BASE}/white/marketing/teambuilding+white.png`,
  },
  {
    id: 'active-search-seo-white',
    label: 'Active Search',
    category: 'seo',
    color: 'white',
    tags: ['search', 'find', 'lookup', 'discovery', 'research', 'query', 'seo'],
    pngUrl: `${BASE}/white/seo/active+search+white.png`,
  },
  {
    id: 'calendar-seo-white',
    label: 'Calendar',
    category: 'seo',
    color: 'white',
    tags: ['calendar', 'schedule', 'planning', 'time', 'date', 'events', 'meeting'],
    pngUrl: `${BASE}/white/seo/calendar+white.png`,
  },
  {
    id: 'chat-seo-white',
    label: 'Chat',
    category: 'seo',
    color: 'white',
    tags: ['chat', 'message', 'conversation', 'communication', 'support', 'dialogue'],
    pngUrl: `${BASE}/white/seo/chat+white.png`,
  },
  {
    id: 'cloud-sync-seo-white',
    label: 'Cloud Sync',
    category: 'seo',
    color: 'white',
    tags: ['cloud', 'sync', 'backup', 'storage', 'integration', 'data', 'upload'],
    pngUrl: `${BASE}/white/seo/cloud+sync+white.png`,
  },
  {
    id: 'coding-seo-white',
    label: 'Coding',
    category: 'seo',
    color: 'white',
    tags: ['coding', 'programming', 'development', 'engineering', 'software', 'code'],
    pngUrl: `${BASE}/white/seo/coding+white.png`,
  },
  {
    id: 'data-analytics-seo-white',
    label: 'Data Analytics',
    category: 'seo',
    color: 'white',
    tags: ['data', 'analytics', 'insights', 'metrics', 'reporting', 'analysis', 'dashboard'],
    pngUrl: `${BASE}/white/seo/data+analytics+white.png`,
  },
  {
    id: 'data-download-seo-white',
    label: 'Data Download',
    category: 'seo',
    color: 'white',
    tags: ['data', 'download', 'export', 'transfer', 'extract', 'retrieve'],
    pngUrl: `${BASE}/white/seo/data+download+white.png`,
  },
  {
    id: 'email-marketing-option1-seo-white',
    label: 'Email Marketing Option 1',
    category: 'seo',
    color: 'white',
    tags: ['email', 'marketing', 'newsletter', 'outreach', 'campaign', 'inbox'],
    pngUrl: `${BASE}/white/seo/email+marketing+option+1+white.png`,
  },
  {
    id: 'email-marketing-option2-seo-white',
    label: 'Email Marketing Option 2',
    category: 'seo',
    color: 'white',
    tags: ['email', 'marketing', 'newsletter', 'outreach', 'campaign', 'inbox'],
    pngUrl: `${BASE}/white/seo/email+marketing+option+2+white.png`,
  },
  {
    id: 'increased-performance-seo-white',
    label: 'Increased Performance',
    category: 'seo',
    color: 'white',
    tags: ['performance', 'increase', 'improve', 'optimize', 'boost', 'efficiency', 'results'],
    pngUrl: `${BASE}/white/seo/increased+performance+white.png`,
  },
  {
    id: 'link-seo-white',
    label: 'Link',
    category: 'seo',
    color: 'white',
    tags: ['link', 'connect', 'integration', 'url', 'backlink', 'reference', 'chain'],
    pngUrl: `${BASE}/white/seo/link+white.png`,
  },
  {
    id: 'online-support-seo-white',
    label: 'Online Support',
    category: 'seo',
    color: 'white',
    tags: ['online', 'support', 'helpdesk', 'service', 'chat', 'remote', 'assistance'],
    pngUrl: `${BASE}/white/seo/online+support+white.png`,
  },
  {
    id: 'seo-location-seo-white',
    label: 'SEO Location',
    category: 'seo',
    color: 'white',
    tags: ['seo', 'location', 'local', 'geo', 'map', 'targeting', 'search'],
    pngUrl: `${BASE}/white/seo/seo+location+white.png`,
  },
  {
    id: 'seo-option1-seo-white',
    label: 'SEO Option 1',
    category: 'seo',
    color: 'white',
    tags: ['seo', 'optimization', 'search', 'ranking', 'organic', 'visibility', 'engine'],
    pngUrl: `${BASE}/white/seo/seo+option+1+white.png`,
  },
  {
    id: 'seo-option2-seo-white',
    label: 'SEO Option 2',
    category: 'seo',
    color: 'white',
    tags: ['seo', 'optimization', 'search', 'ranking', 'organic', 'visibility', 'engine'],
    pngUrl: `${BASE}/white/seo/seo+option+2+white.png`,
  },
  {
    id: 'seo-plugin-option2-seo-white',
    label: 'SEO Plugin Option 2',
    category: 'seo',
    color: 'white',
    tags: ['seo', 'plugin', 'tool', 'optimization', 'search', 'ranking', 'engine'],
    pngUrl: `${BASE}/white/seo/seo+plugin+option+2+white.png`,
  },
  {
    id: 'seo-plugin-seo-white',
    label: 'SEO Plugin',
    category: 'seo',
    color: 'white',
    tags: ['seo', 'plugin', 'tool', 'optimization', 'search', 'ranking', 'engine'],
    pngUrl: `${BASE}/white/seo/seo+plugin+white.png`,
  },
  {
    id: 'seo-seo-white',
    label: 'SEO',
    category: 'seo',
    color: 'white',
    tags: ['seo', 'search engine optimization', 'ranking', 'organic', 'visibility', 'traffic'],
    pngUrl: `${BASE}/white/seo/seo+white.png`,
  },
  {
    id: 'target-seo-white',
    label: 'Target',
    category: 'seo',
    color: 'white',
    tags: ['target', 'audience', 'goal', 'focus', 'aim', 'precision', 'segment'],
    pngUrl: `${BASE}/white/seo/target+white.png`,
  },
  {
    id: 'time-management-seo-white',
    label: 'Time Management',
    category: 'seo',
    color: 'white',
    tags: ['time', 'management', 'efficiency', 'planning', 'deadline', 'schedule', 'productivity'],
    pngUrl: `${BASE}/white/seo/time+management+white.png`,
  },
  {
    id: 'traffic-seo-white',
    label: 'Traffic',
    category: 'seo',
    color: 'white',
    tags: ['traffic', 'visits', 'sessions', 'users', 'web', 'inbound', 'acquisition'],
    pngUrl: `${BASE}/white/seo/traffic+white.png`,
  },
  {
    id: 'video-marketing-seo-white',
    label: 'Video Marketing',
    category: 'seo',
    color: 'white',
    tags: ['video', 'marketing', 'content', 'media', 'youtube', 'visual', 'campaign'],
    pngUrl: `${BASE}/white/seo/video+marketing+white.png`,
  },
  {
    id: 'web-optimisation-seo-white',
    label: 'Web Optimisation',
    category: 'seo',
    color: 'white',
    tags: ['web', 'optimisation', 'performance', 'speed', 'core web vitals', 'loading', 'site'],
    pngUrl: `${BASE}/white/seo/web+optimisation+white.png`,
  },
]

export const iconLibrary: IconLibrary = {
  version: '1.0',
  baseUrl: BASE,
  icons: [...blackIcons, ...whiteIcons],
}
