/**
 * Generated by `bun run generate:block-successors` from the block registry.
 * Do not edit this file directly.
 *
 * Maps a retired block type to the *terminal* type an access-control decision
 * about it is made against — `sunset.replacedBy`, followed transitively. It
 * exists as a generated projection because `lib/permission-groups/` may not
 * import `blocks/`; see `scripts/generate-block-successors.ts`.
 */
export const BLOCK_ACCESS_SUCCESSORS: Record<string, string> = {
  api_trigger: 'start_trigger',
  chat_trigger: 'start_trigger',
  file: 'file_v5',
  file_v2: 'file_v5',
  file_v3: 'file_v5',
  file_v4: 'file_v5',
  gmail: 'gmail_v2',
  google_calendar: 'google_calendar_v2',
  google_sheets: 'google_sheets_v2',
  human_in_the_loop: 'human_in_the_loop_v2',
  image_generator: 'image_generator_v2',
  input_trigger: 'start_trigger',
  logs: 'logs_v2',
  manual_trigger: 'start_trigger',
  notion: 'notion_v2',
  openai: 'embeddings',
  router: 'router_v2',
  starter: 'start_trigger',
  stt: 'stt_v2',
  table: 'table_v2',
  workflow: 'workflow_input',
}
