import {
  airtableCreateRecordsTool,
  airtableDeleteRecordsTool,
  airtableGetBaseSchemaTool,
  airtableGetRecordTool,
  airtableListBasesTool,
  airtableListRecordsTool,
  airtableListTablesTool,
  airtableUpdateMultipleRecordsTool,
  airtableUpdateRecordTool,
  airtableUpsertRecordsTool,
} from '@/tools/airtable'
import {
  calcomCancelBookingTool,
  calcomConfirmBookingTool,
  calcomCreateBookingTool,
  calcomCreateEventTypeTool,
  calcomCreateScheduleTool,
  calcomDeclineBookingTool,
  calcomDeleteEventTypeTool,
  calcomDeleteScheduleTool,
  calcomGetBookingTool,
  calcomGetDefaultScheduleTool,
  calcomGetEventTypeTool,
  calcomGetScheduleTool,
  calcomGetSlotsTool,
  calcomListBookingsTool,
  calcomListEventTypesTool,
  calcomListSchedulesTool,
  calcomRescheduleBookingTool,
  calcomUpdateEventTypeTool,
  calcomUpdateScheduleTool,
} from '@/tools/calcom'
import {
  calendlyCancelEventTool,
  calendlyCreateEventInviteeTool,
  calendlyCreateInviteeNoShowTool,
  calendlyCreateSchedulingLinkTool,
  calendlyCreateWebhookTool,
  calendlyDeleteInviteeNoShowTool,
  calendlyDeleteWebhookTool,
  calendlyGetCurrentUserTool,
  calendlyGetEventInviteeTool,
  calendlyGetEventTypeTool,
  calendlyGetScheduledEventTool,
  calendlyGetUserTool,
  calendlyListEventInviteesTool,
  calendlyListEventTypeAvailableTimesTool,
  calendlyListEventTypesTool,
  calendlyListOrganizationMembershipsTool,
  calendlyListRoutingFormSubmissionsTool,
  calendlyListRoutingFormsTool,
  calendlyListScheduledEventsTool,
  calendlyListUserAvailabilitySchedulesTool,
  calendlyListUserBusyTimesTool,
  calendlyListWebhooksTool,
} from '@/tools/calendly'
import {
  deploymentsDeployTool,
  deploymentsGetVersionTool,
  deploymentsListVersionsTool,
  deploymentsPromoteTool,
  deploymentsUndeployTool,
} from '@/tools/deployments'
import {
  elevenLabsAudioIsolationTool,
  elevenLabsEditVoiceSettingsTool,
  elevenLabsGetUserTool,
  elevenLabsGetVoiceSettingsTool,
  elevenLabsGetVoiceTool,
  elevenLabsListModelsTool,
  elevenLabsListVoicesTool,
  elevenLabsSoundEffectsTool,
  elevenLabsSpeechToSpeechTool,
  elevenLabsTtsTool,
} from '@/tools/elevenlabs'
import {
  embeddingsCohereTool,
  embeddingsGeminiTool,
  embeddingsMistralTool,
  embeddingsOllamaTool,
  embeddingsOpenAITool,
  embeddingsOpenRouterTool,
} from '@/tools/embeddings'
import {
  exaAgentTool,
  exaAnswerTool,
  exaFindSimilarLinksTool,
  exaGetContentsTool,
  exaSearchTool,
} from '@/tools/exa'
import {
  fileAppendTool,
  fileCompressTool,
  fileCreateFolderTool,
  fileDecompressTool,
  fileDeleteFolderTool,
  fileEditTool,
  fileFetchTool,
  fileGetContentTool,
  fileGetTool,
  fileListTool,
  fileManageSharingTool,
  fileMoveTool,
  fileParserV2Tool,
  fileParserV3Tool,
  fileParseTool,
  fileReadTool,
  fileRestoreFolderTool,
  fileSearchTool,
  fileUpdateFolderTool,
  fileWriteTool,
} from '@/tools/file'
import {
  firecrawlAgentTool,
  firecrawlBatchScrapeStatusTool,
  firecrawlBatchScrapeTool,
  firecrawlCancelCrawlTool,
  firecrawlCrawlStatusTool,
  firecrawlCrawlTool,
  firecrawlCreditUsageTool,
  firecrawlExtractStatusTool,
  firecrawlExtractTool,
  firecrawlMapTool,
  firecrawlParseTool,
  firecrawlScrapeTool,
  firecrawlSearchTool,
} from '@/tools/firecrawl'
import { functionExecuteTool } from '@/tools/function'
import {
  gmailAddLabelTool,
  gmailAddLabelV2Tool,
  gmailArchiveTool,
  gmailArchiveV2Tool,
  gmailCreateLabelV2Tool,
  gmailDeleteDraftV2Tool,
  gmailDeleteLabelV2Tool,
  gmailDeleteTool,
  gmailDeleteV2Tool,
  gmailDraftTool,
  gmailDraftV2Tool,
  gmailEditDraftV2Tool,
  gmailGetDraftV2Tool,
  gmailGetThreadV2Tool,
  gmailListDraftsV2Tool,
  gmailListLabelsV2Tool,
  gmailListThreadsV2Tool,
  gmailMarkReadTool,
  gmailMarkReadV2Tool,
  gmailMarkUnreadTool,
  gmailMarkUnreadV2Tool,
  gmailMoveTool,
  gmailMoveV2Tool,
  gmailReadTool,
  gmailReadV2Tool,
  gmailRemoveLabelTool,
  gmailRemoveLabelV2Tool,
  gmailSearchTool,
  gmailSearchV2Tool,
  gmailSendTool,
  gmailSendV2Tool,
  gmailTrashThreadV2Tool,
  gmailUnarchiveTool,
  gmailUnarchiveV2Tool,
  gmailUntrashThreadV2Tool,
  gmailUpdateLabelV2Tool,
} from '@/tools/gmail'
import {
  googleCalendarCreateCalendarTool,
  googleCalendarCreateCalendarV2Tool,
  googleCalendarCreateTool,
  googleCalendarCreateV2Tool,
  googleCalendarDeleteCalendarTool,
  googleCalendarDeleteCalendarV2Tool,
  googleCalendarDeleteTool,
  googleCalendarDeleteV2Tool,
  googleCalendarFreeBusyTool,
  googleCalendarFreeBusyV2Tool,
  googleCalendarGetTool,
  googleCalendarGetV2Tool,
  googleCalendarInstancesTool,
  googleCalendarInstancesV2Tool,
  googleCalendarInviteTool,
  googleCalendarInviteV2Tool,
  googleCalendarListAclTool,
  googleCalendarListAclV2Tool,
  googleCalendarListCalendarsTool,
  googleCalendarListCalendarsV2Tool,
  googleCalendarListTool,
  googleCalendarListV2Tool,
  googleCalendarMoveTool,
  googleCalendarMoveV2Tool,
  googleCalendarQuickAddTool,
  googleCalendarQuickAddV2Tool,
  googleCalendarRespondTool,
  googleCalendarRespondV2Tool,
  googleCalendarShareCalendarTool,
  googleCalendarShareCalendarV2Tool,
  googleCalendarUnshareCalendarTool,
  googleCalendarUnshareCalendarV2Tool,
  googleCalendarUpdateAclTool,
  googleCalendarUpdateAclV2Tool,
  googleCalendarUpdateCalendarTool,
  googleCalendarUpdateCalendarV2Tool,
  googleCalendarUpdateTool,
  googleCalendarUpdateV2Tool,
} from '@/tools/google_calendar'
import {
  googleDocsCreateNamedRangeTool,
  googleDocsCreateParagraphBulletsTool,
  googleDocsCreateTool,
  googleDocsDeleteContentRangeTool,
  googleDocsDeleteNamedRangeTool,
  googleDocsDeleteParagraphBulletsTool,
  googleDocsInsertImageTool,
  googleDocsInsertPageBreakTool,
  googleDocsInsertTableTool,
  googleDocsInsertTextTool,
  googleDocsReadTool,
  googleDocsReplaceTextTool,
  googleDocsUpdateParagraphStyleTool,
  googleDocsUpdateTextStyleTool,
  googleDocsWriteTool,
} from '@/tools/google_docs'
import {
  googleDriveCopyTool,
  googleDriveCreateCommentTool,
  googleDriveCreateFolderTool,
  googleDriveDeleteCommentTool,
  googleDriveDeleteTool,
  googleDriveDownloadTool,
  googleDriveExportTool,
  googleDriveGetAboutTool,
  googleDriveGetContentTool,
  googleDriveGetFileTool,
  googleDriveGetRevisionTool,
  googleDriveListCommentsTool,
  googleDriveListPermissionsTool,
  googleDriveListRevisionsTool,
  googleDriveListTool,
  googleDriveMoveTool,
  googleDriveSearchTool,
  googleDriveShareTool,
  googleDriveTrashTool,
  googleDriveUnshareTool,
  googleDriveUntrashTool,
  googleDriveUpdateTool,
  googleDriveUploadTool,
} from '@/tools/google_drive'
import {
  googleFormsBatchUpdateTool,
  googleFormsCreateFormTool,
  googleFormsCreateWatchTool,
  googleFormsDeleteWatchTool,
  googleFormsGetFormTool,
  googleFormsGetResponsesTool,
  googleFormsListWatchesTool,
  googleFormsRenewWatchTool,
  googleFormsSetPublishSettingsTool,
} from '@/tools/google_forms'
import {
  googleMapsAirQualityTool,
  googleMapsDirectionsTool,
  googleMapsDistanceMatrixTool,
  googleMapsElevationTool,
  googleMapsGeocodeTool,
  googleMapsGeolocateTool,
  googleMapsPlaceDetailsTool,
  googleMapsPlacesNearbyTool,
  googleMapsPlacesSearchTool,
  googleMapsPollenTool,
  googleMapsReverseGeocodeTool,
  googleMapsSnapToRoadsTool,
  googleMapsSolarTool,
  googleMapsSpeedLimitsTool,
  googleMapsTimezoneTool,
  googleMapsValidateAddressTool,
} from '@/tools/google_maps'
import {
  googleSheetsAppendTool,
  googleSheetsAppendV2Tool,
  googleSheetsBatchClearV2Tool,
  googleSheetsBatchGetV2Tool,
  googleSheetsBatchUpdateV2Tool,
  googleSheetsClearV2Tool,
  googleSheetsCopySheetV2Tool,
  googleSheetsCreateSpreadsheetV2Tool,
  googleSheetsDeleteRowsV2Tool,
  googleSheetsDeleteSheetV2Tool,
  googleSheetsDeleteSpreadsheetV2Tool,
  googleSheetsGetSpreadsheetV2Tool,
  googleSheetsReadTool,
  googleSheetsReadV2Tool,
  googleSheetsUpdateTool,
  googleSheetsUpdateV2Tool,
  googleSheetsWriteTool,
  googleSheetsWriteV2Tool,
} from '@/tools/google_sheets'
import { guardrailsValidateTool } from '@/tools/guardrails'
import { httpRequestTool, webhookRequestTool } from '@/tools/http'
import {
  hubspotAddListMembershipsTool,
  hubspotCreateAppointmentTool,
  hubspotCreateAssociationTool,
  hubspotCreateCompanyTool,
  hubspotCreateContactTool,
  hubspotCreateDealTool,
  hubspotCreateEmailTool,
  hubspotCreateLineItemTool,
  hubspotCreateListTool,
  hubspotCreateNoteTool,
  hubspotCreateTicketTool,
  hubspotDeleteAssociationTool,
  hubspotDeleteCompanyTool,
  hubspotDeleteContactTool,
  hubspotDeleteDealTool,
  hubspotDeleteLineItemTool,
  hubspotDeleteTicketTool,
  hubspotGetAppointmentTool,
  hubspotGetAssociationLabelsTool,
  hubspotGetCartTool,
  hubspotGetCompanyTool,
  hubspotGetContactTool,
  hubspotGetDealTool,
  hubspotGetEmailTool,
  hubspotGetLineItemTool,
  hubspotGetListMembershipsTool,
  hubspotGetListTool,
  hubspotGetMarketingEventTool,
  hubspotGetNoteTool,
  hubspotGetPropertiesTool,
  hubspotGetQuoteTool,
  hubspotGetTicketTool,
  hubspotGetUsersTool,
  hubspotListAppointmentsTool,
  hubspotListAssociationsTool,
  hubspotListCartsTool,
  hubspotListCompaniesTool,
  hubspotListContactsTool,
  hubspotListDealsTool,
  hubspotListEmailsTool,
  hubspotListLineItemsTool,
  hubspotListListsTool,
  hubspotListMarketingEventsTool,
  hubspotListNotesTool,
  hubspotListOwnersTool,
  hubspotListQuotesTool,
  hubspotListTicketsTool,
  hubspotRemoveListMembershipsTool,
  hubspotSearchCompaniesTool,
  hubspotSearchContactsTool,
  hubspotSearchDealsTool,
  hubspotSearchEmailsTool,
  hubspotSearchLineItemsTool,
  hubspotSearchNotesTool,
  hubspotSearchQuotesTool,
  hubspotSearchTicketsTool,
  hubspotUpdateAppointmentTool,
  hubspotUpdateCompanyTool,
  hubspotUpdateContactTool,
  hubspotUpdateDealTool,
  hubspotUpdateLineItemTool,
  hubspotUpdateTicketTool,
} from '@/tools/hubspot'
import { imageGenerateTool } from '@/tools/image'
import {
  instagramDeleteCommentTool,
  instagramDownloadMediaTool,
  instagramGetAccountInsightsTool,
  instagramGetContainerStatusTool,
  instagramGetConversationMessagesTool,
  instagramGetMediaInsightsTool,
  instagramGetMediaTool,
  instagramGetMessageTool,
  instagramGetProfileTool,
  instagramGetPublishingLimitTool,
  instagramHideCommentTool,
  instagramListCommentsTool,
  instagramListConversationsTool,
  instagramListMediaTool,
  instagramListStoriesTool,
  instagramPrivateReplyTool,
  instagramPublishCarouselTool,
  instagramPublishImageTool,
  instagramPublishReelTool,
  instagramPublishStoryTool,
  instagramPublishVideoTool,
  instagramReplyToCommentTool,
  instagramSendTextMessageTool,
  instagramSetCommentsEnabledTool,
} from '@/tools/instagram'
import {
  knowledgeCreateDocumentTool,
  knowledgeDeleteChunkTool,
  knowledgeDeleteDocumentTool,
  knowledgeGetConnectorTool,
  knowledgeGetDocumentTool,
  knowledgeListChunksTool,
  knowledgeListConnectorsTool,
  knowledgeListDocumentsTool,
  knowledgeListTagsTool,
  knowledgeSearchTool,
  knowledgeTriggerSyncTool,
  knowledgeUpdateChunkTool,
  knowledgeUploadChunkTool,
  knowledgeUpsertDocumentTool,
} from '@/tools/knowledge'
import { llmChatTool } from '@/tools/llm'
import {
  logsGetExecutionTool,
  logsGetRunDetailsTool,
  logsGetTool,
  logsQueryRunsTool,
  logsQueryTool,
} from '@/tools/logs'
import { mcpListOperationsTool, mcpRunOperationTool } from '@/tools/mcp'
import { memoryAddTool, memoryDeleteTool, memoryGetAllTool, memoryGetTool } from '@/tools/memory'
import {
  mysqlDeleteTool,
  mysqlExecuteTool,
  mysqlInsertTool,
  mysqlIntrospectTool,
  mysqlQueryTool,
  mysqlUpdateTool,
} from '@/tools/mysql'
import {
  notionAddDatabaseRowTool,
  notionAddDatabaseRowV2Tool,
  notionAppendBlocksTool,
  notionAppendBlocksV2Tool,
  notionCreateCommentTool,
  notionCreateCommentV2Tool,
  notionCreateDatabaseTool,
  notionCreateDatabaseV2Tool,
  notionCreatePageTool,
  notionCreatePageV2Tool,
  notionDeleteBlockTool,
  notionDeleteBlockV2Tool,
  notionListCommentsTool,
  notionListCommentsV2Tool,
  notionListUsersTool,
  notionListUsersV2Tool,
  notionQueryDatabaseTool,
  notionQueryDatabaseV2Tool,
  notionReadDatabaseTool,
  notionReadDatabaseV2Tool,
  notionReadTool,
  notionReadV2Tool,
  notionRetrieveBlockChildrenTool,
  notionRetrieveBlockChildrenV2Tool,
  notionRetrieveBlockTool,
  notionRetrieveBlockV2Tool,
  notionRetrieveUserTool,
  notionRetrieveUserV2Tool,
  notionSearchTool,
  notionSearchV2Tool,
  notionUpdateBlockTool,
  notionUpdateBlockV2Tool,
  notionUpdatePageTool,
  notionUpdatePageV2Tool,
  notionWriteTool,
  notionWriteV2Tool,
} from '@/tools/notion'
import { openAIEmbeddingsTool, openAIImageTool } from '@/tools/openai'
import {
  pipedriveCreateActivityTool,
  pipedriveCreateDealTool,
  pipedriveCreateLeadTool,
  pipedriveCreateProjectTool,
  pipedriveDeleteLeadTool,
  pipedriveGetActivitiesTool,
  pipedriveGetAllDealsTool,
  pipedriveGetDealTool,
  pipedriveGetFilesTool,
  pipedriveGetLeadsTool,
  pipedriveGetMailMessagesTool,
  pipedriveGetMailThreadTool,
  pipedriveGetPipelineDealsTool,
  pipedriveGetPipelinesTool,
  pipedriveGetProjectsTool,
  pipedriveUpdateActivityTool,
  pipedriveUpdateDealTool,
  pipedriveUpdateLeadTool,
} from '@/tools/pipedrive'
import {
  postgresDeleteTool,
  postgresExecuteTool,
  postgresInsertTool,
  postgresIntrospectTool,
  postgresQueryTool,
  postgresUpdateTool,
} from '@/tools/postgresql'
import { searchTool } from '@/tools/search'
import { serperSearchTool } from '@/tools/serper'
import {
  shopifyAdjustInventoryTool,
  shopifyCancelOrderTool,
  shopifyCreateCustomerTool,
  shopifyCreateFulfillmentTool,
  shopifyCreateProductTool,
  shopifyDeleteCustomerTool,
  shopifyDeleteProductTool,
  shopifyGetCollectionTool,
  shopifyGetCustomerTool,
  shopifyGetInventoryLevelTool,
  shopifyGetOrderTool,
  shopifyGetProductTool,
  shopifyListCollectionsTool,
  shopifyListCustomersTool,
  shopifyListInventoryItemsTool,
  shopifyListLocationsTool,
  shopifyListOrdersTool,
  shopifyListProductsTool,
  shopifyUpdateCustomerTool,
  shopifyUpdateOrderTool,
  shopifyUpdateProductTool,
} from '@/tools/shopify'
import { smtpSendMailTool } from '@/tools/smtp'
import {
  assemblyaiSttTool,
  assemblyaiSttV2Tool,
  deepgramSttTool,
  deepgramSttV2Tool,
  elevenLabsSttTool,
  elevenLabsSttV2Tool,
  geminiSttTool,
  geminiSttV2Tool,
  whisperSttTool,
  whisperSttV2Tool,
} from '@/tools/stt'
import {
  supabaseCountTool,
  supabaseDeleteTool,
  supabaseGetRowTool,
  supabaseInsertTool,
  supabaseIntrospectTool,
  supabaseInvokeFunctionTool,
  supabaseQueryTool,
  supabaseRpcTool,
  supabaseStorageCopyTool,
  supabaseStorageCreateBucketTool,
  supabaseStorageCreateSignedUploadUrlTool,
  supabaseStorageCreateSignedUrlTool,
  supabaseStorageDeleteBucketTool,
  supabaseStorageDeleteTool,
  supabaseStorageDownloadTool,
  supabaseStorageEmptyBucketTool,
  supabaseStorageGetPublicUrlTool,
  supabaseStorageListBucketsTool,
  supabaseStorageListTool,
  supabaseStorageMoveTool,
  supabaseStorageUpdateBucketTool,
  supabaseStorageUploadTool,
  supabaseTextSearchTool,
  supabaseUpdateTool,
  supabaseUpsertTool,
  supabaseVectorSearchTool,
} from '@/tools/supabase'
import {
  tableBatchInsertRowsTool,
  tableCreateTool,
  tableDeleteRowsByFilterTool,
  tableDeleteRowTool,
  tableGetRowTool,
  tableGetSchemaTool,
  tableInsertRowTool,
  tableListTool,
  tableQueryRowsTool,
  tableQueryRowsV2Tool,
  tableUpdateRowsByFilterTool,
  tableUpdateRowTool,
  tableUpsertRowTool,
} from '@/tools/table'
import {
  telegramCopyMessageTool,
  telegramDeleteMessageTool,
  telegramEditMessageTextTool,
  telegramForwardMessageTool,
  telegramGetChatMemberTool,
  telegramGetChatTool,
  telegramMessageTool,
  telegramPinMessageTool,
  telegramSendAnimationTool,
  telegramSendAudioTool,
  telegramSendChatActionTool,
  telegramSendContactTool,
  telegramSendDocumentTool,
  telegramSendLocationTool,
  telegramSendPhotoTool,
  telegramSendPollTool,
  telegramSendVideoTool,
  telegramSetMessageReactionTool,
  telegramUnpinMessageTool,
} from '@/tools/telegram'
import { thinkingTool } from '@/tools/thinking'
import {
  trelloAddChecklistItemTool,
  trelloAddChecklistTool,
  trelloAddCommentTool,
  trelloAddLabelTool,
  trelloAddMemberTool,
  trelloCreateBoardTool,
  trelloCreateCardTool,
  trelloCreateListTool,
  trelloDeleteCardTool,
  trelloGetActionsTool,
  trelloGetBoardTool,
  trelloGetCardTool,
  trelloListCardsTool,
  trelloListListsTool,
  trelloListMembersTool,
  trelloRemoveLabelTool,
  trelloRemoveMemberTool,
  trelloSearchTool,
  trelloUpdateCardTool,
  trelloUpdateChecklistItemTool,
  trelloUpdateListTool,
} from '@/tools/trello'
import {
  azureTtsTool,
  cartesiaTtsTool,
  deepgramTtsTool,
  elevenLabsTtsUnifiedTool,
  googleTtsTool,
  openaiTtsTool,
  playhtTtsTool,
} from '@/tools/tts'
import { sendSMSTool } from '@/tools/twilio'
import type { ExecutableToolConfig } from '@/tools/types'
import { visionTool, visionToolV2 } from '@/tools/vision'
import {
  whatsappGetMediaTool,
  whatsappMarkReadTool,
  whatsappSendInteractiveTool,
  whatsappSendMediaTool,
  whatsappSendMessageTool,
  whatsappSendReactionTool,
  whatsappSendTemplateTool,
  whatsappUploadMediaTool,
} from '@/tools/whatsapp'
import {
  wordpressCreateCategoryTool,
  wordpressCreateCommentTool,
  wordpressCreatePageTool,
  wordpressCreatePostTool,
  wordpressCreateTagTool,
  wordpressDeleteCategoryTool,
  wordpressDeleteCommentTool,
  wordpressDeleteMediaTool,
  wordpressDeletePageTool,
  wordpressDeletePostTool,
  wordpressDeleteTagTool,
  wordpressGetCategoryTool,
  wordpressGetCurrentUserTool,
  wordpressGetMediaTool,
  wordpressGetPageTool,
  wordpressGetPostTool,
  wordpressGetTagTool,
  wordpressGetUserTool,
  wordpressListCategoriesTool,
  wordpressListCommentsTool,
  wordpressListMediaTool,
  wordpressListPagesTool,
  wordpressListPostsTool,
  wordpressListTagsTool,
  wordpressListUsersTool,
  wordpressSearchContentTool,
  wordpressUpdateCategoryTool,
  wordpressUpdateCommentTool,
  wordpressUpdatePageTool,
  wordpressUpdatePostTool,
  wordpressUpdateTagTool,
  wordpressUploadMediaTool,
} from '@/tools/wordpress'
import { customBlockExecutorTool, workflowExecutorTool } from '@/tools/workflow'
import {
  zoomCreateMeetingTool,
  zoomDeleteMeetingTool,
  zoomDeleteRecordingTool,
  zoomGetMeetingInvitationTool,
  zoomGetMeetingRecordingsTool,
  zoomGetMeetingTool,
  zoomListMeetingsTool,
  zoomListPastParticipantsTool,
  zoomListRecordingsTool,
  zoomUpdateMeetingTool,
} from '@/tools/zoom'

// Registry of all available tools
export const tools: Record<string, ExecutableToolConfig> = {
  openai_embeddings: openAIEmbeddingsTool,
  http_request: httpRequestTool,
  webhook_request: webhookRequestTool,
  llm_chat: llmChatTool,
  function_execute: functionExecuteTool,
  vision_tool: visionTool,
  vision_tool_v2: visionToolV2,
  file_parser: fileParseTool,
  file_parser_v2: fileParserV2Tool,
  file_parser_v3: fileParserV3Tool,
  file_append: fileAppendTool,
  file_compress: fileCompressTool,
  file_create_folder: fileCreateFolderTool,
  file_decompress: fileDecompressTool,
  file_edit: fileEditTool,
  file_delete_folder: fileDeleteFolderTool,
  file_fetch: fileFetchTool,
  file_get: fileGetTool,
  file_get_content: fileGetContentTool,
  file_list: fileListTool,
  file_read: fileReadTool,
  file_search: fileSearchTool,
  file_manage_sharing: fileManageSharingTool,
  file_move: fileMoveTool,
  file_restore_folder: fileRestoreFolderTool,
  file_update_folder: fileUpdateFolderTool,
  file_write: fileWriteTool,
  firecrawl_scrape: firecrawlScrapeTool,
  firecrawl_search: firecrawlSearchTool,
  firecrawl_crawl: firecrawlCrawlTool,
  firecrawl_crawl_status: firecrawlCrawlStatusTool,
  firecrawl_cancel_crawl: firecrawlCancelCrawlTool,
  firecrawl_batch_scrape: firecrawlBatchScrapeTool,
  firecrawl_batch_scrape_status: firecrawlBatchScrapeStatusTool,
  firecrawl_map: firecrawlMapTool,
  firecrawl_extract: firecrawlExtractTool,
  firecrawl_extract_status: firecrawlExtractStatusTool,
  firecrawl_agent: firecrawlAgentTool,
  firecrawl_parse: firecrawlParseTool,
  firecrawl_credit_usage: firecrawlCreditUsageTool,
  guardrails_validate: guardrailsValidateTool,
  instagram_delete_comment: instagramDeleteCommentTool,
  instagram_download_media: instagramDownloadMediaTool,
  instagram_get_account_insights: instagramGetAccountInsightsTool,
  instagram_get_container_status: instagramGetContainerStatusTool,
  instagram_get_conversation_messages: instagramGetConversationMessagesTool,
  instagram_get_media: instagramGetMediaTool,
  instagram_get_media_insights: instagramGetMediaInsightsTool,
  instagram_get_message: instagramGetMessageTool,
  instagram_get_profile: instagramGetProfileTool,
  instagram_get_publishing_limit: instagramGetPublishingLimitTool,
  instagram_hide_comment: instagramHideCommentTool,
  instagram_list_comments: instagramListCommentsTool,
  instagram_list_conversations: instagramListConversationsTool,
  instagram_list_media: instagramListMediaTool,
  instagram_list_stories: instagramListStoriesTool,
  instagram_private_reply: instagramPrivateReplyTool,
  instagram_publish_carousel: instagramPublishCarouselTool,
  instagram_publish_image: instagramPublishImageTool,
  instagram_publish_reel: instagramPublishReelTool,
  instagram_publish_story: instagramPublishStoryTool,
  instagram_publish_video: instagramPublishVideoTool,
  instagram_reply_to_comment: instagramReplyToCommentTool,
  instagram_send_text_message: instagramSendTextMessageTool,
  instagram_set_comments_enabled: instagramSetCommentsEnabledTool,
  logs_query: logsQueryTool,
  logs_query_runs: logsQueryRunsTool,
  logs_get: logsGetTool,
  logs_get_execution: logsGetExecutionTool,
  logs_get_run_details: logsGetRunDetailsTool,
  smtp_send_mail: smtpSendMailTool,
  serper_search: serperSearchTool,
  supabase_query: supabaseQueryTool,
  supabase_insert: supabaseInsertTool,
  supabase_get_row: supabaseGetRowTool,
  supabase_update: supabaseUpdateTool,
  supabase_delete: supabaseDeleteTool,
  supabase_upsert: supabaseUpsertTool,
  supabase_count: supabaseCountTool,
  supabase_text_search: supabaseTextSearchTool,
  supabase_vector_search: supabaseVectorSearchTool,
  supabase_rpc: supabaseRpcTool,
  supabase_introspect: supabaseIntrospectTool,
  supabase_invoke_function: supabaseInvokeFunctionTool,
  supabase_storage_upload: supabaseStorageUploadTool,
  supabase_storage_download: supabaseStorageDownloadTool,
  supabase_storage_list: supabaseStorageListTool,
  supabase_storage_delete: supabaseStorageDeleteTool,
  supabase_storage_move: supabaseStorageMoveTool,
  supabase_storage_copy: supabaseStorageCopyTool,
  supabase_storage_create_bucket: supabaseStorageCreateBucketTool,
  supabase_storage_update_bucket: supabaseStorageUpdateBucketTool,
  supabase_storage_empty_bucket: supabaseStorageEmptyBucketTool,
  supabase_storage_list_buckets: supabaseStorageListBucketsTool,
  supabase_storage_delete_bucket: supabaseStorageDeleteBucketTool,
  supabase_storage_get_public_url: supabaseStorageGetPublicUrlTool,
  supabase_storage_create_signed_url: supabaseStorageCreateSignedUrlTool,
  supabase_storage_create_signed_upload_url: supabaseStorageCreateSignedUploadUrlTool,
  calendly_get_current_user: calendlyGetCurrentUserTool,
  calendly_get_user: calendlyGetUserTool,
  calendly_list_event_types: calendlyListEventTypesTool,
  calendly_get_event_type: calendlyGetEventTypeTool,
  calendly_list_event_type_available_times: calendlyListEventTypeAvailableTimesTool,
  calendly_list_scheduled_events: calendlyListScheduledEventsTool,
  calendly_get_scheduled_event: calendlyGetScheduledEventTool,
  calendly_list_event_invitees: calendlyListEventInviteesTool,
  calendly_get_event_invitee: calendlyGetEventInviteeTool,
  calendly_create_event_invitee: calendlyCreateEventInviteeTool,
  calendly_cancel_event: calendlyCancelEventTool,
  calendly_create_invitee_no_show: calendlyCreateInviteeNoShowTool,
  calendly_delete_invitee_no_show: calendlyDeleteInviteeNoShowTool,
  calendly_create_scheduling_link: calendlyCreateSchedulingLinkTool,
  calendly_list_user_busy_times: calendlyListUserBusyTimesTool,
  calendly_list_user_availability_schedules: calendlyListUserAvailabilitySchedulesTool,
  calendly_list_organization_memberships: calendlyListOrganizationMembershipsTool,
  calendly_list_routing_forms: calendlyListRoutingFormsTool,
  calendly_list_routing_form_submissions: calendlyListRoutingFormSubmissionsTool,
  calendly_list_webhooks: calendlyListWebhooksTool,
  calendly_create_webhook: calendlyCreateWebhookTool,
  calendly_delete_webhook: calendlyDeleteWebhookTool,
  calcom_create_booking: calcomCreateBookingTool,
  calcom_get_booking: calcomGetBookingTool,
  calcom_list_bookings: calcomListBookingsTool,
  calcom_cancel_booking: calcomCancelBookingTool,
  calcom_reschedule_booking: calcomRescheduleBookingTool,
  calcom_confirm_booking: calcomConfirmBookingTool,
  calcom_decline_booking: calcomDeclineBookingTool,
  calcom_create_event_type: calcomCreateEventTypeTool,
  calcom_get_event_type: calcomGetEventTypeTool,
  calcom_list_event_types: calcomListEventTypesTool,
  calcom_update_event_type: calcomUpdateEventTypeTool,
  calcom_delete_event_type: calcomDeleteEventTypeTool,
  calcom_create_schedule: calcomCreateScheduleTool,
  calcom_get_schedule: calcomGetScheduleTool,
  calcom_list_schedules: calcomListSchedulesTool,
  calcom_update_schedule: calcomUpdateScheduleTool,
  calcom_delete_schedule: calcomDeleteScheduleTool,
  calcom_get_default_schedule: calcomGetDefaultScheduleTool,
  calcom_get_slots: calcomGetSlotsTool,
  notion_read: notionReadTool,
  notion_read_database: notionReadDatabaseTool,
  notion_write: notionWriteTool,
  notion_create_page: notionCreatePageTool,
  notion_query_database: notionQueryDatabaseTool,
  notion_search: notionSearchTool,
  notion_create_database: notionCreateDatabaseTool,
  notion_add_database_row: notionAddDatabaseRowTool,
  notion_update_page: notionUpdatePageTool,
  notion_append_blocks: notionAppendBlocksTool,
  notion_retrieve_block: notionRetrieveBlockTool,
  notion_retrieve_block_children: notionRetrieveBlockChildrenTool,
  notion_update_block: notionUpdateBlockTool,
  notion_delete_block: notionDeleteBlockTool,
  notion_create_comment: notionCreateCommentTool,
  notion_list_comments: notionListCommentsTool,
  notion_list_users: notionListUsersTool,
  notion_retrieve_user: notionRetrieveUserTool,
  notion_read_v2: notionReadV2Tool,
  notion_read_database_v2: notionReadDatabaseV2Tool,
  notion_write_v2: notionWriteV2Tool,
  notion_create_page_v2: notionCreatePageV2Tool,
  notion_query_database_v2: notionQueryDatabaseV2Tool,
  notion_search_v2: notionSearchV2Tool,
  notion_create_database_v2: notionCreateDatabaseV2Tool,
  notion_update_page_v2: notionUpdatePageV2Tool,
  notion_add_database_row_v2: notionAddDatabaseRowV2Tool,
  notion_append_blocks_v2: notionAppendBlocksV2Tool,
  notion_retrieve_block_v2: notionRetrieveBlockV2Tool,
  notion_retrieve_block_children_v2: notionRetrieveBlockChildrenV2Tool,
  notion_update_block_v2: notionUpdateBlockV2Tool,
  notion_delete_block_v2: notionDeleteBlockV2Tool,
  notion_create_comment_v2: notionCreateCommentV2Tool,
  notion_list_comments_v2: notionListCommentsV2Tool,
  notion_list_users_v2: notionListUsersV2Tool,
  notion_retrieve_user_v2: notionRetrieveUserV2Tool,
  gmail_send: gmailSendTool,
  gmail_send_v2: gmailSendV2Tool,
  gmail_read: gmailReadTool,
  gmail_read_v2: gmailReadV2Tool,
  gmail_search: gmailSearchTool,
  gmail_search_v2: gmailSearchV2Tool,
  gmail_draft: gmailDraftTool,
  gmail_draft_v2: gmailDraftV2Tool,
  gmail_move: gmailMoveTool,
  gmail_move_v2: gmailMoveV2Tool,
  gmail_mark_read: gmailMarkReadTool,
  gmail_mark_read_v2: gmailMarkReadV2Tool,
  gmail_mark_unread: gmailMarkUnreadTool,
  gmail_mark_unread_v2: gmailMarkUnreadV2Tool,
  gmail_archive: gmailArchiveTool,
  gmail_archive_v2: gmailArchiveV2Tool,
  gmail_unarchive: gmailUnarchiveTool,
  gmail_unarchive_v2: gmailUnarchiveV2Tool,
  gmail_delete: gmailDeleteTool,
  gmail_delete_v2: gmailDeleteV2Tool,
  gmail_add_label: gmailAddLabelTool,
  gmail_add_label_v2: gmailAddLabelV2Tool,
  gmail_remove_label: gmailRemoveLabelTool,
  gmail_remove_label_v2: gmailRemoveLabelV2Tool,
  gmail_create_label_v2: gmailCreateLabelV2Tool,
  gmail_delete_draft_v2: gmailDeleteDraftV2Tool,
  gmail_delete_label_v2: gmailDeleteLabelV2Tool,
  gmail_edit_draft_v2: gmailEditDraftV2Tool,
  gmail_get_draft_v2: gmailGetDraftV2Tool,
  gmail_get_thread_v2: gmailGetThreadV2Tool,
  gmail_list_drafts_v2: gmailListDraftsV2Tool,
  gmail_list_labels_v2: gmailListLabelsV2Tool,
  gmail_list_threads_v2: gmailListThreadsV2Tool,
  gmail_trash_thread_v2: gmailTrashThreadV2Tool,
  gmail_untrash_thread_v2: gmailUntrashThreadV2Tool,
  gmail_update_label_v2: gmailUpdateLabelV2Tool,
  whatsapp_send_message: whatsappSendMessageTool,
  whatsapp_send_template: whatsappSendTemplateTool,
  whatsapp_send_media: whatsappSendMediaTool,
  whatsapp_send_interactive: whatsappSendInteractiveTool,
  whatsapp_send_reaction: whatsappSendReactionTool,
  whatsapp_mark_read: whatsappMarkReadTool,
  whatsapp_upload_media: whatsappUploadMediaTool,
  whatsapp_get_media: whatsappGetMediaTool,
  pipedrive_create_activity: pipedriveCreateActivityTool,
  pipedrive_create_deal: pipedriveCreateDealTool,
  pipedrive_create_lead: pipedriveCreateLeadTool,
  pipedrive_create_project: pipedriveCreateProjectTool,
  pipedrive_delete_lead: pipedriveDeleteLeadTool,
  pipedrive_get_activities: pipedriveGetActivitiesTool,
  pipedrive_get_all_deals: pipedriveGetAllDealsTool,
  pipedrive_get_deal: pipedriveGetDealTool,
  pipedrive_get_files: pipedriveGetFilesTool,
  pipedrive_get_leads: pipedriveGetLeadsTool,
  pipedrive_get_mail_messages: pipedriveGetMailMessagesTool,
  pipedrive_get_mail_thread: pipedriveGetMailThreadTool,
  pipedrive_get_pipeline_deals: pipedriveGetPipelineDealsTool,
  pipedrive_get_pipelines: pipedriveGetPipelinesTool,
  pipedrive_get_projects: pipedriveGetProjectsTool,
  pipedrive_update_activity: pipedriveUpdateActivityTool,
  pipedrive_update_deal: pipedriveUpdateDealTool,
  pipedrive_update_lead: pipedriveUpdateLeadTool,
  postgresql_query: postgresQueryTool,
  postgresql_insert: postgresInsertTool,
  postgresql_update: postgresUpdateTool,
  postgresql_delete: postgresDeleteTool,
  postgresql_execute: postgresExecuteTool,
  postgresql_introspect: postgresIntrospectTool,
  deployments_deploy: deploymentsDeployTool,
  deployments_get_version: deploymentsGetVersionTool,
  deployments_list_versions: deploymentsListVersionsTool,
  deployments_promote: deploymentsPromoteTool,
  deployments_undeploy: deploymentsUndeployTool,
  mysql_query: mysqlQueryTool,
  mysql_insert: mysqlInsertTool,
  mysql_update: mysqlUpdateTool,
  mysql_delete: mysqlDeleteTool,
  mysql_execute: mysqlExecuteTool,
  mysql_introspect: mysqlIntrospectTool,
  embeddings_openai: embeddingsOpenAITool,
  embeddings_gemini: embeddingsGeminiTool,
  embeddings_cohere: embeddingsCohereTool,
  embeddings_mistral: embeddingsMistralTool,
  embeddings_openrouter: embeddingsOpenRouterTool,
  embeddings_ollama: embeddingsOllamaTool,
  exa_search: exaSearchTool,
  exa_get_contents: exaGetContentsTool,
  exa_find_similar_links: exaFindSimilarLinksTool,
  exa_answer: exaAnswerTool,
  exa_agent: exaAgentTool,
  google_drive_copy: googleDriveCopyTool,
  google_drive_create_comment: googleDriveCreateCommentTool,
  google_drive_create_folder: googleDriveCreateFolderTool,
  google_drive_delete: googleDriveDeleteTool,
  google_drive_delete_comment: googleDriveDeleteCommentTool,
  google_drive_download: googleDriveDownloadTool,
  google_drive_export: googleDriveExportTool,
  google_drive_get_about: googleDriveGetAboutTool,
  google_drive_get_content: googleDriveGetContentTool,
  google_drive_get_file: googleDriveGetFileTool,
  google_drive_get_revision: googleDriveGetRevisionTool,
  google_drive_list: googleDriveListTool,
  google_drive_list_comments: googleDriveListCommentsTool,
  google_drive_list_permissions: googleDriveListPermissionsTool,
  google_drive_list_revisions: googleDriveListRevisionsTool,
  google_drive_move: googleDriveMoveTool,
  google_drive_search: googleDriveSearchTool,
  google_drive_share: googleDriveShareTool,
  google_drive_trash: googleDriveTrashTool,
  google_drive_unshare: googleDriveUnshareTool,
  google_drive_untrash: googleDriveUntrashTool,
  google_drive_update: googleDriveUpdateTool,
  google_drive_upload: googleDriveUploadTool,
  google_docs_read: googleDocsReadTool,
  google_docs_write: googleDocsWriteTool,
  google_docs_create: googleDocsCreateTool,
  google_docs_insert_text: googleDocsInsertTextTool,
  google_docs_replace_text: googleDocsReplaceTextTool,
  google_docs_insert_table: googleDocsInsertTableTool,
  google_docs_insert_image: googleDocsInsertImageTool,
  google_docs_insert_page_break: googleDocsInsertPageBreakTool,
  google_docs_update_text_style: googleDocsUpdateTextStyleTool,
  google_docs_update_paragraph_style: googleDocsUpdateParagraphStyleTool,
  google_docs_create_paragraph_bullets: googleDocsCreateParagraphBulletsTool,
  google_docs_delete_paragraph_bullets: googleDocsDeleteParagraphBulletsTool,
  google_docs_delete_content_range: googleDocsDeleteContentRangeTool,
  google_docs_create_named_range: googleDocsCreateNamedRangeTool,
  google_docs_delete_named_range: googleDocsDeleteNamedRangeTool,
  google_maps_air_quality: googleMapsAirQualityTool,
  google_maps_directions: googleMapsDirectionsTool,
  google_maps_distance_matrix: googleMapsDistanceMatrixTool,
  google_maps_elevation: googleMapsElevationTool,
  google_maps_geocode: googleMapsGeocodeTool,
  google_maps_geolocate: googleMapsGeolocateTool,
  google_maps_place_details: googleMapsPlaceDetailsTool,
  google_maps_places_nearby: googleMapsPlacesNearbyTool,
  google_maps_places_search: googleMapsPlacesSearchTool,
  google_maps_pollen: googleMapsPollenTool,
  google_maps_reverse_geocode: googleMapsReverseGeocodeTool,
  google_maps_snap_to_roads: googleMapsSnapToRoadsTool,
  google_maps_solar: googleMapsSolarTool,
  google_maps_speed_limits: googleMapsSpeedLimitsTool,
  google_maps_timezone: googleMapsTimezoneTool,
  google_maps_validate_address: googleMapsValidateAddressTool,
  google_sheets_read: googleSheetsReadTool,
  google_sheets_write: googleSheetsWriteTool,
  google_sheets_update: googleSheetsUpdateTool,
  google_sheets_append: googleSheetsAppendTool,
  google_sheets_read_v2: googleSheetsReadV2Tool,
  google_sheets_write_v2: googleSheetsWriteV2Tool,
  google_sheets_update_v2: googleSheetsUpdateV2Tool,
  google_sheets_append_v2: googleSheetsAppendV2Tool,
  google_sheets_clear_v2: googleSheetsClearV2Tool,
  google_sheets_get_spreadsheet_v2: googleSheetsGetSpreadsheetV2Tool,
  google_sheets_create_spreadsheet_v2: googleSheetsCreateSpreadsheetV2Tool,
  google_sheets_batch_get_v2: googleSheetsBatchGetV2Tool,
  google_sheets_batch_update_v2: googleSheetsBatchUpdateV2Tool,
  google_sheets_batch_clear_v2: googleSheetsBatchClearV2Tool,
  google_sheets_copy_sheet_v2: googleSheetsCopySheetV2Tool,
  google_sheets_delete_rows_v2: googleSheetsDeleteRowsV2Tool,
  google_sheets_delete_sheet_v2: googleSheetsDeleteSheetV2Tool,
  google_sheets_delete_spreadsheet_v2: googleSheetsDeleteSpreadsheetV2Tool,
  trello_list_lists: trelloListListsTool,
  trello_list_cards: trelloListCardsTool,
  trello_create_card: trelloCreateCardTool,
  trello_update_card: trelloUpdateCardTool,
  trello_delete_card: trelloDeleteCardTool,
  trello_get_actions: trelloGetActionsTool,
  trello_add_comment: trelloAddCommentTool,
  trello_create_board: trelloCreateBoardTool,
  trello_get_board: trelloGetBoardTool,
  trello_create_list: trelloCreateListTool,
  trello_update_list: trelloUpdateListTool,
  trello_get_card: trelloGetCardTool,
  trello_add_checklist: trelloAddChecklistTool,
  trello_add_checklist_item: trelloAddChecklistItemTool,
  trello_update_checklist_item: trelloUpdateChecklistItemTool,
  trello_add_label: trelloAddLabelTool,
  trello_remove_label: trelloRemoveLabelTool,
  trello_add_member: trelloAddMemberTool,
  trello_remove_member: trelloRemoveMemberTool,
  trello_list_members: trelloListMembersTool,
  trello_search: trelloSearchTool,
  twilio_send_sms: sendSMSTool,
  airtable_create_records: airtableCreateRecordsTool,
  airtable_delete_records: airtableDeleteRecordsTool,
  airtable_get_base_schema: airtableGetBaseSchemaTool,
  airtable_get_record: airtableGetRecordTool,
  airtable_list_bases: airtableListBasesTool,
  airtable_list_records: airtableListRecordsTool,
  airtable_list_tables: airtableListTablesTool,
  airtable_update_multiple_records: airtableUpdateMultipleRecordsTool,
  airtable_update_record: airtableUpdateRecordTool,
  airtable_upsert_records: airtableUpsertRecordsTool,
  thinking_tool: thinkingTool,
  mcp_list_operations: mcpListOperationsTool,
  mcp_run_operation: mcpRunOperationTool,
  memory_add: memoryAddTool,
  memory_get: memoryGetTool,
  memory_get_all: memoryGetAllTool,
  memory_delete: memoryDeleteTool,
  knowledge_search: knowledgeSearchTool,
  knowledge_upload_chunk: knowledgeUploadChunkTool,
  knowledge_create_document: knowledgeCreateDocumentTool,
  knowledge_list_tags: knowledgeListTagsTool,
  knowledge_list_documents: knowledgeListDocumentsTool,
  knowledge_get_document: knowledgeGetDocumentTool,
  knowledge_delete_document: knowledgeDeleteDocumentTool,
  knowledge_list_chunks: knowledgeListChunksTool,
  knowledge_update_chunk: knowledgeUpdateChunkTool,
  knowledge_delete_chunk: knowledgeDeleteChunkTool,
  knowledge_list_connectors: knowledgeListConnectorsTool,
  knowledge_get_connector: knowledgeGetConnectorTool,
  knowledge_trigger_sync: knowledgeTriggerSyncTool,
  knowledge_upsert_document: knowledgeUpsertDocumentTool,
  search_tool: searchTool,
  elevenlabs_tts: elevenLabsTtsTool,
  elevenlabs_list_voices: elevenLabsListVoicesTool,
  elevenlabs_get_voice: elevenLabsGetVoiceTool,
  elevenlabs_get_voice_settings: elevenLabsGetVoiceSettingsTool,
  elevenlabs_edit_voice_settings: elevenLabsEditVoiceSettingsTool,
  elevenlabs_list_models: elevenLabsListModelsTool,
  elevenlabs_get_user: elevenLabsGetUserTool,
  elevenlabs_sound_effects: elevenLabsSoundEffectsTool,
  elevenlabs_speech_to_speech: elevenLabsSpeechToSpeechTool,
  elevenlabs_audio_isolation: elevenLabsAudioIsolationTool,
  stt_whisper: whisperSttTool,
  stt_whisper_v2: whisperSttV2Tool,
  stt_deepgram: deepgramSttTool,
  stt_deepgram_v2: deepgramSttV2Tool,
  stt_elevenlabs: elevenLabsSttTool,
  stt_elevenlabs_v2: elevenLabsSttV2Tool,
  stt_assemblyai: assemblyaiSttTool,
  stt_assemblyai_v2: assemblyaiSttV2Tool,
  stt_gemini: geminiSttTool,
  stt_gemini_v2: geminiSttV2Tool,
  tts_openai: openaiTtsTool,
  tts_deepgram: deepgramTtsTool,
  tts_elevenlabs: elevenLabsTtsUnifiedTool,
  tts_cartesia: cartesiaTtsTool,
  tts_google: googleTtsTool,
  tts_azure: azureTtsTool,
  tts_playht: playhtTtsTool,
  telegram_message: telegramMessageTool,
  telegram_delete_message: telegramDeleteMessageTool,
  telegram_send_audio: telegramSendAudioTool,
  telegram_send_animation: telegramSendAnimationTool,
  telegram_send_photo: telegramSendPhotoTool,
  telegram_send_video: telegramSendVideoTool,
  telegram_send_document: telegramSendDocumentTool,
  telegram_edit_message_text: telegramEditMessageTextTool,
  telegram_forward_message: telegramForwardMessageTool,
  telegram_copy_message: telegramCopyMessageTool,
  telegram_send_location: telegramSendLocationTool,
  telegram_send_contact: telegramSendContactTool,
  telegram_send_poll: telegramSendPollTool,
  telegram_pin_message: telegramPinMessageTool,
  telegram_unpin_message: telegramUnpinMessageTool,
  telegram_set_message_reaction: telegramSetMessageReactionTool,
  telegram_send_chat_action: telegramSendChatActionTool,
  telegram_get_chat: telegramGetChatTool,
  telegram_get_chat_member: telegramGetChatMemberTool,
  image_generate: imageGenerateTool,
  openai_image: openAIImageTool,
  shopify_create_product: shopifyCreateProductTool,
  shopify_get_product: shopifyGetProductTool,
  shopify_list_products: shopifyListProductsTool,
  shopify_update_product: shopifyUpdateProductTool,
  shopify_delete_product: shopifyDeleteProductTool,
  shopify_get_order: shopifyGetOrderTool,
  shopify_list_orders: shopifyListOrdersTool,
  shopify_update_order: shopifyUpdateOrderTool,
  shopify_cancel_order: shopifyCancelOrderTool,
  shopify_create_customer: shopifyCreateCustomerTool,
  shopify_get_customer: shopifyGetCustomerTool,
  shopify_list_customers: shopifyListCustomersTool,
  shopify_update_customer: shopifyUpdateCustomerTool,
  shopify_delete_customer: shopifyDeleteCustomerTool,
  shopify_get_inventory_level: shopifyGetInventoryLevelTool,
  shopify_adjust_inventory: shopifyAdjustInventoryTool,
  shopify_list_inventory_items: shopifyListInventoryItemsTool,
  shopify_list_locations: shopifyListLocationsTool,
  shopify_create_fulfillment: shopifyCreateFulfillmentTool,
  shopify_list_collections: shopifyListCollectionsTool,
  shopify_get_collection: shopifyGetCollectionTool,
  google_calendar_create: googleCalendarCreateTool,
  google_calendar_create_v2: googleCalendarCreateV2Tool,
  google_calendar_create_calendar: googleCalendarCreateCalendarTool,
  google_calendar_create_calendar_v2: googleCalendarCreateCalendarV2Tool,
  google_calendar_delete: googleCalendarDeleteTool,
  google_calendar_delete_v2: googleCalendarDeleteV2Tool,
  google_calendar_delete_calendar: googleCalendarDeleteCalendarTool,
  google_calendar_delete_calendar_v2: googleCalendarDeleteCalendarV2Tool,
  google_calendar_freebusy: googleCalendarFreeBusyTool,
  google_calendar_freebusy_v2: googleCalendarFreeBusyV2Tool,
  google_calendar_get: googleCalendarGetTool,
  google_calendar_get_v2: googleCalendarGetV2Tool,
  google_calendar_instances: googleCalendarInstancesTool,
  google_calendar_instances_v2: googleCalendarInstancesV2Tool,
  google_calendar_invite: googleCalendarInviteTool,
  google_calendar_invite_v2: googleCalendarInviteV2Tool,
  google_calendar_list: googleCalendarListTool,
  google_calendar_list_v2: googleCalendarListV2Tool,
  google_calendar_list_acl: googleCalendarListAclTool,
  google_calendar_list_acl_v2: googleCalendarListAclV2Tool,
  google_calendar_list_calendars: googleCalendarListCalendarsTool,
  google_calendar_list_calendars_v2: googleCalendarListCalendarsV2Tool,
  google_calendar_move: googleCalendarMoveTool,
  google_calendar_move_v2: googleCalendarMoveV2Tool,
  google_calendar_quick_add: googleCalendarQuickAddTool,
  google_calendar_quick_add_v2: googleCalendarQuickAddV2Tool,
  google_calendar_respond: googleCalendarRespondTool,
  google_calendar_respond_v2: googleCalendarRespondV2Tool,
  google_calendar_share_calendar: googleCalendarShareCalendarTool,
  google_calendar_share_calendar_v2: googleCalendarShareCalendarV2Tool,
  google_calendar_unshare_calendar: googleCalendarUnshareCalendarTool,
  google_calendar_unshare_calendar_v2: googleCalendarUnshareCalendarV2Tool,
  google_calendar_update: googleCalendarUpdateTool,
  google_calendar_update_v2: googleCalendarUpdateV2Tool,
  google_calendar_update_acl: googleCalendarUpdateAclTool,
  google_calendar_update_acl_v2: googleCalendarUpdateAclV2Tool,
  google_calendar_update_calendar: googleCalendarUpdateCalendarTool,
  google_calendar_update_calendar_v2: googleCalendarUpdateCalendarV2Tool,
  google_forms_get_responses: googleFormsGetResponsesTool,
  google_forms_get_form: googleFormsGetFormTool,
  google_forms_create_form: googleFormsCreateFormTool,
  google_forms_batch_update: googleFormsBatchUpdateTool,
  google_forms_set_publish_settings: googleFormsSetPublishSettingsTool,
  google_forms_create_watch: googleFormsCreateWatchTool,
  google_forms_list_watches: googleFormsListWatchesTool,
  google_forms_delete_watch: googleFormsDeleteWatchTool,
  google_forms_renew_watch: googleFormsRenewWatchTool,
  workflow_executor: workflowExecutorTool,
  deployed_block_executor: customBlockExecutorTool,
  wordpress_create_post: wordpressCreatePostTool,
  wordpress_update_post: wordpressUpdatePostTool,
  wordpress_delete_post: wordpressDeletePostTool,
  wordpress_get_post: wordpressGetPostTool,
  wordpress_list_posts: wordpressListPostsTool,
  wordpress_create_page: wordpressCreatePageTool,
  wordpress_update_page: wordpressUpdatePageTool,
  wordpress_delete_page: wordpressDeletePageTool,
  wordpress_get_page: wordpressGetPageTool,
  wordpress_list_pages: wordpressListPagesTool,
  wordpress_upload_media: wordpressUploadMediaTool,
  wordpress_get_media: wordpressGetMediaTool,
  wordpress_list_media: wordpressListMediaTool,
  wordpress_delete_media: wordpressDeleteMediaTool,
  wordpress_create_comment: wordpressCreateCommentTool,
  wordpress_list_comments: wordpressListCommentsTool,
  wordpress_update_comment: wordpressUpdateCommentTool,
  wordpress_delete_comment: wordpressDeleteCommentTool,
  wordpress_create_category: wordpressCreateCategoryTool,
  wordpress_list_categories: wordpressListCategoriesTool,
  wordpress_get_category: wordpressGetCategoryTool,
  wordpress_update_category: wordpressUpdateCategoryTool,
  wordpress_delete_category: wordpressDeleteCategoryTool,
  wordpress_create_tag: wordpressCreateTagTool,
  wordpress_list_tags: wordpressListTagsTool,
  wordpress_get_tag: wordpressGetTagTool,
  wordpress_update_tag: wordpressUpdateTagTool,
  wordpress_delete_tag: wordpressDeleteTagTool,
  wordpress_get_current_user: wordpressGetCurrentUserTool,
  wordpress_list_users: wordpressListUsersTool,
  wordpress_get_user: wordpressGetUserTool,
  wordpress_search_content: wordpressSearchContentTool,
  hubspot_add_list_memberships: hubspotAddListMembershipsTool,
  hubspot_create_appointment: hubspotCreateAppointmentTool,
  hubspot_create_association: hubspotCreateAssociationTool,
  hubspot_create_company: hubspotCreateCompanyTool,
  hubspot_create_contact: hubspotCreateContactTool,
  hubspot_create_deal: hubspotCreateDealTool,
  hubspot_create_email: hubspotCreateEmailTool,
  hubspot_create_line_item: hubspotCreateLineItemTool,
  hubspot_create_list: hubspotCreateListTool,
  hubspot_create_note: hubspotCreateNoteTool,
  hubspot_create_ticket: hubspotCreateTicketTool,
  hubspot_delete_association: hubspotDeleteAssociationTool,
  hubspot_delete_company: hubspotDeleteCompanyTool,
  hubspot_delete_contact: hubspotDeleteContactTool,
  hubspot_delete_deal: hubspotDeleteDealTool,
  hubspot_delete_line_item: hubspotDeleteLineItemTool,
  hubspot_delete_ticket: hubspotDeleteTicketTool,
  hubspot_get_appointment: hubspotGetAppointmentTool,
  hubspot_get_association_labels: hubspotGetAssociationLabelsTool,
  hubspot_get_cart: hubspotGetCartTool,
  hubspot_get_company: hubspotGetCompanyTool,
  hubspot_get_contact: hubspotGetContactTool,
  hubspot_get_deal: hubspotGetDealTool,
  hubspot_get_email: hubspotGetEmailTool,
  hubspot_get_line_item: hubspotGetLineItemTool,
  hubspot_get_list: hubspotGetListTool,
  hubspot_get_list_memberships: hubspotGetListMembershipsTool,
  hubspot_get_marketing_event: hubspotGetMarketingEventTool,
  hubspot_get_note: hubspotGetNoteTool,
  hubspot_get_properties: hubspotGetPropertiesTool,
  hubspot_get_quote: hubspotGetQuoteTool,
  hubspot_get_ticket: hubspotGetTicketTool,
  hubspot_get_users: hubspotGetUsersTool,
  hubspot_list_appointments: hubspotListAppointmentsTool,
  hubspot_list_associations: hubspotListAssociationsTool,
  hubspot_list_carts: hubspotListCartsTool,
  hubspot_list_companies: hubspotListCompaniesTool,
  hubspot_list_contacts: hubspotListContactsTool,
  hubspot_list_deals: hubspotListDealsTool,
  hubspot_list_emails: hubspotListEmailsTool,
  hubspot_list_line_items: hubspotListLineItemsTool,
  hubspot_list_lists: hubspotListListsTool,
  hubspot_list_marketing_events: hubspotListMarketingEventsTool,
  hubspot_list_notes: hubspotListNotesTool,
  hubspot_list_owners: hubspotListOwnersTool,
  hubspot_list_quotes: hubspotListQuotesTool,
  hubspot_list_tickets: hubspotListTicketsTool,
  hubspot_remove_list_memberships: hubspotRemoveListMembershipsTool,
  hubspot_search_companies: hubspotSearchCompaniesTool,
  hubspot_search_contacts: hubspotSearchContactsTool,
  hubspot_search_deals: hubspotSearchDealsTool,
  hubspot_search_emails: hubspotSearchEmailsTool,
  hubspot_search_line_items: hubspotSearchLineItemsTool,
  hubspot_search_notes: hubspotSearchNotesTool,
  hubspot_search_quotes: hubspotSearchQuotesTool,
  hubspot_search_tickets: hubspotSearchTicketsTool,
  hubspot_update_appointment: hubspotUpdateAppointmentTool,
  hubspot_update_company: hubspotUpdateCompanyTool,
  hubspot_update_contact: hubspotUpdateContactTool,
  hubspot_update_deal: hubspotUpdateDealTool,
  hubspot_update_line_item: hubspotUpdateLineItemTool,
  hubspot_update_ticket: hubspotUpdateTicketTool,
  table_create: tableCreateTool,
  table_list: tableListTool,
  table_insert_row: tableInsertRowTool,
  table_batch_insert_rows: tableBatchInsertRowsTool,
  table_upsert_row: tableUpsertRowTool,
  table_update_row: tableUpdateRowTool,
  table_update_rows_by_filter: tableUpdateRowsByFilterTool,
  table_delete_row: tableDeleteRowTool,
  table_delete_rows_by_filter: tableDeleteRowsByFilterTool,
  table_query_rows: tableQueryRowsTool,
  table_query_rows_v2: tableQueryRowsV2Tool,
  table_get_row: tableGetRowTool,
  table_get_schema: tableGetSchemaTool,
  zoom_create_meeting: zoomCreateMeetingTool,
  zoom_list_meetings: zoomListMeetingsTool,
  zoom_get_meeting: zoomGetMeetingTool,
  zoom_update_meeting: zoomUpdateMeetingTool,
  zoom_delete_meeting: zoomDeleteMeetingTool,
  zoom_get_meeting_invitation: zoomGetMeetingInvitationTool,
  zoom_list_recordings: zoomListRecordingsTool,
  zoom_get_meeting_recordings: zoomGetMeetingRecordingsTool,
  zoom_delete_recording: zoomDeleteRecordingTool,
  zoom_list_past_participants: zoomListPastParticipantsTool,
}
